title: My Visualization Site
email: chinmay@example.com
description: >
  A collection of my data stories and visualizations built for my course.
baseurl: "/my-visualization-site"
url: "https://chinmay921.github.io"
author: Chinmay Dongarkar

theme: minima

plugins:
  - jekyll-feed

markdown: kramdown

# ✅ Override layout defaults to use your own local layout files
defaults:
  - scope:
      path: ""
    values:
      layout: default
